<?php

namespace Proximit\Bundle\UserBundle\Listener;

use Proximit\Bundle\UserBundle\Entity\User;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use FOS\UserBundle\FOSUserEvents;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserListener implements EventSubscriberInterface
{
    protected $mailer;

    public function __construct(\Swift_Mailer $mailer)
    {
        $this->mailer = $mailer;
    }
    
    public static function getSubscribedEvents()
    {
        return array(
            FOSUserEvents::REGISTRATION_SUCCESS => 'onFosUserRegistrationSuccess',
        );
    }

    public function onFosUserRegistrationSuccess()
    {
        $message = \Swift_Message::newInstance()
            ->setSubject('Confirmation de votre création de compte pour la bibliothèque MediaBundle')
            ->setFrom('noreply@mediabundle.com')
            ->setTo('adeline.bechade@proximit.fr')
            ->setBody('Votre compte vient d\'être créé, vous pouvez maintenant vous connecter à l\'application MediaBundle');
        
        //$this->mailer->send($message);
    }
}
